repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.9
  hooks:
    - id: ruff
      args: [ --config=pyproject.toml, --fix, --exit-non-zero-on-fix, --select=F401,I001 ]
      types_or: [ python, pyi, jupyter ]

- repo: local
  hooks:
    - id: uv
      name: uv
      entry: uv sync --all-extras
      language: system
      pass_filenames: false
    - id: run-{{cookiecutter.directory_name}}-tests
      name: Run {{cookiecutter.directory_name}} tests
      language: system
      entry: bash bin/run_tests.sh
      types: [ python ]
      files: ^{{cookiecutter.directory_name}}/.*\.py$      
      pass_filenames: true
