repos:
- repo: local
  hooks:
    - id: uv
      name: uv
      entry: uv sync --all-extras
      language: system
      pass_filenames: false
    - id: ruff
      name: ruff
      entry: uv run ruff check --fix --select F401,I .
      language: system
      pass_filenames: false
    - id: tests
      name: tests
      language: system
      entry: bash bin/run_tests.sh
      types: [ python ]
      files: ^{{cookiecutter.directory_name}}/.*\.py$      
      pass_filenames: true
