[hcp]

  [hcp.mid_cpu]
  nodes = 1
  cpus-per-task = 4
  mem = "64G"
  time = "12:00:00"
  partition = "cpu_p"
  qos = "cpu_normal"
  nice = 10000

  [hcp.mid_gpu]
  nodes = 1
  cpus-per-task = 4
  mem = "64G"
  time = "12:00:00"
  partition = "gpu_p"
  gres = "gpu:1"
  qos = "gpu_normal"
  nice = 10000

  [hcp.big_gpu]
  nodes = 1
  cpus-per-task = 4
  mem = "64G"
  time = "12:00:00"
  partition = "gpu_p"
  gres = "gpu:1"
  qos = "gpu_normal"
  constraint = "a100_80gb"
  nice = 10000

  [hcp.big_gpu_long]
  nodes = 1
  cpus-per-task = 4
  mem = "64G"
  time = "24:00:00"
  partition = "gpu_p"
  gres = "gpu:1"
  qos = "gpu_normal"
  constraint = "a100_80gb"
  nice = 10000


  [hcp.two_big_gpu]
  nodes = 1
  cpus-per-task = 4
  mem = "160G"
  time = "12:00:00"
  partition = "gpu_p"
  gres = "gpu:2"
  qos = "gpu_normal"
  constraint = "a100_80gb"
  nice = 10000
  
  [hcp.two_big_gpu_long]
  nodes = 1
  cpus-per-task = 4
  mem = "160G"
  time = "24:00:00"
  partition = "gpu_p"
  gres = "gpu:2"
  qos = "gpu_normal"
  constraint = "a100_80gb"
  nice = 10000
